apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-server
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: demo-server
  endpoints:
    - port: web